### ISSUE TITLE
Build fails - Cordova@11 android@11

### ISSUE THREAD

**Issue by pixellet14** [sarriaroman/photoviewer#228]
I get the following error on build attempt

Could not find method compile() for arguments [com.commit451:PhotoView:1.2.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by sarriaroman** [comment]
Solved in 1.3.0

**Comment by pixellet14** [comment]
No the issue isn't solved... i am still getting the same error. please can u help?

**Comment by pixellet14** [comment]
also, unable to install the plugin using the command cordova plugin add com-sarriaroman-photoviewer@1.3.0

**Comment by pixellet14** [comment]
Yayyyyyy it's working!!!! THANKS!!!

**Comment by sarriaroman** [comment]
Nice to hear that it works! can I close the issue then?

**Comment by pixellet14** [comment]
yes yes plsss close it

**Comment by matteobarale** [comment]
Sorry but how can I install version 1.3 through npm? 
https://www.npmjs.com/package/com-sarriaroman-photoviewer?activeTab=versions
here I see 1.2.5 as the latest release

**Comment by pixellet14** [comment]
> Sorry but how can I install version 1.3 through npm? https://www.npmjs.com/package/com-sarriaroman-photoviewer?activeTab=versions here I see 1.2.5 as the latest release

no no no don't do that! I did the same mistake...just install via git link as mentioned there already... it works for me (cordova 11 & android@latest)

**Comment by matteobarale** [comment]
Yes it's work also for me, but it's difficult to maintain in that way

**Comment by ShriVarkhedi** [comment]
Hi @pixellet14, Could you please share the GIT command to install the latest version ? I couldn't find any as such. 

Thanks in advance.
